ProgressTestWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgressTestWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ProgressTestWeb/Controllers/ProgressController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProgressTestWeb.db;

namespace ProgressTestWeb.Controllers
{
    public class ProgressController : Controller
    {
        // GET: Progress
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetAjaxTest1(string param)
        {
            try
            {
                var db = new webtestEntities();
                var q = from b in db.progress_test where b.no == param select b.count;
                var cnt = q.Single();

                return Json(new { donePercent = cnt.ToString(), finish = (cnt == 100) });
            }
            catch
            {

            }
            return Json("");
        }

        public ActionResult StartProgress()
        {
            var psi = new ProcessStartInfo();
            psi.FileName = "ProgressTestExe";
            var guid = Guid.NewGuid();
            string new_id = guid.ToString("N");
            psi.UseShellExecute = false;

            psi.Arguments = new_id;
            var p = Process.Start(psi);

            ViewBag.ProgressID = new_id;

            return View();
        }

        public ActionResult Download(string id)
        {
#if DEBUG
            string path = @"C:\Users\ono\HW\web.config";
#else
            string path = @"C:\ProgressTest\" + id + ".txt";
#endif
            return File(path, "application/pdf", "test.txt");
        }
    }
}

ProgressTestWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProgressTestWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProgressTestWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ProgressTestWeb/Views/Progress/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>
    ファイル出力を行う外部EXE起動のプログレスバー表示を
    AJAXで出来るか？
</h2>

    ボタンを押すとここの値が更新されます
<input type="text" value="1" id="textbox" name="str" />

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="更新" id="getButton" class="btn btn-default" />
    </div>
    <div class="list-group ">
        @Html.ActionLink("ロード直後から開始", "StartProgress", "Progress", null, new { @class = "list-group-item mt-4", target = "_blank" })
        <input type="submit" value="ダウンロード" id="download" class="btn btn-default list-group-item mt-4" />
    </div>
</div>


<script>
    my_valu = 1;
$(function () {
    $('#getButton').click(function () {

        //$('#textbox').val("hogehoge");
        @*$.get('@Url.Action("GetAjaxTest1", "Home")',
            { text: $('#textbox').val() },
            function (data) {
                //console.log(JSON.stringify(data));
                $('#textbox').val(data['returnText']);
            }
        );*@

        setInterval(
            function () {
                $.ajax({
                    url: "GetAjaxTest1",
                    type: 'POST',
                    dataType: 'json',
                    data: my_valu ,
                    timout: 500,
                    success: function (data) {
                        $('#textbox').val(data['returnText']);
                        my_valu = data['returnText'];
                    }
                });
            }, 100
        );
    });

    $('#download').click(function () {
        //$.get("download/" + "1234");
        window.location.href = "download/" + "1234";
    });
});
</script>

ProgressTestWeb/Views/Progress/StartProgress.cshtml
@{
    ViewBag.Title = "StartProgress";
}

<h2>ロード直後からプログレスバーが回転</h2>

@ViewBag.ProgressID

<div class="progress">
    <div class="progress-bar" id="progress" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
</div>
<input type="button" value="閉じる" class="btn-info" onclick="close_page();"/>

<script>
    let done_flag = false;
    $(window).on('load', function () {
        console.log('on load');
        setInterval(
            function () {
                if (!done_flag) {
                    $.ajax({
                        url: "GetAjaxTest1",
                        type: 'POST',
                        dataType: 'json',
                        data: { param: '@ViewBag.ProgressID' },
                        timout: 500,
                        success: function (data) {
                            let hoge = data['donePercent'];
                            $('#progress')
                                .text(hoge + '%')
                                .css('width', hoge + '%')
                                .prop('aria-valuenow', hoge);
                            let done = data['finish'];
                            if (done) {
                                //alert('dekita');
                                done_flag = true;
                                window.location.href = "download/" + '@ViewBag.ProgressID';
                            }
                        }
                    });
                }
            },
            500
        );
    });
    const close_page = () => {
        open(location, '_self').close();
    };
</script>

ProgressTestWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=9" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - マイ ASP.NET アプリケーション</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("アプリケーション名", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("ホーム", "Index", "Home")</li>
                    <li>@Html.ActionLink("詳細", "About", "Home")</li>
                    <li>@Html.ActionLink("問い合わせ", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - マイ ASP.NET アプリケーション</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>